### ISSUE TITLE
map pulsating.

### ISSUE THREAD

**Issue by vladyxd** [NeenGame/neen-atlasmap#1]
hi. I just added it and I see the map pulsating.

https://streamable.com/xh3qc9

**Comment by vladyxd** [comment]
Update, after double checking the files, I found the issue. 
Not related to the map :)

**Comment by riotxstudios** [comment]
> Update, after double checking the files, I found the issue. Not related to the map :)

can u share what ur error was as mine was also pulsing but idk what is causing the issue

**Comment by vladyxd** [comment]
sure, in my case using qbcore, it was this:
```lua
-- qb-hud/client.lua
CreateThread(function()
    while true do
        SetRadarBigmapEnabled(false, false)
        SetRadarZoom(1200) -- this was set to 1000 and changed to 1200 as said in readme
        Wait(500)
    end
end)

```

**Comment by MrTroeper** [comment]
**Ik de zelfde probleem:**

_Heeft iemand ook de oplosing voor ESX_
